#include "ConfigManager.h"
#include <SD.h>
#include <ArduinoJson.h>
#include "../storage/SDCardManager.h"
#include "Config.h"

static const char* CONFIG_FILE = "/data/config.json";
ConfigManager config;

void ConfigManager::clearChats(){ delete[] data.chats; data.chats=nullptr; data.chatCount=0; }
void ConfigManager::clearCommandRoutes(){ delete[] data.commandRoutes; data.commandRoutes=nullptr; data.commandRouteCount=0; }

bool ConfigManager::addChatInternal(const String& id,const String& name){ if(!id.length())return false; auto* next=new TelegramChatConfig[data.chatCount+1]; if(!next)return false; for(size_t i=0;i<data.chatCount;i++)next[i]=data.chats[i]; next[data.chatCount]={id,name.length()?name:id}; delete[] data.chats; data.chats=next; data.chatCount++; return true; }
bool ConfigManager::addCommandRouteInternal(const String& phrase,const String& url,const String& apiKey,const String& command){ if(!phrase.length()||!url.length()||!command.length())return false; auto* next=new CommandRouteConfig[data.commandRouteCount+1]; if(!next)return false; for(size_t i=0;i<data.commandRouteCount;i++)next[i]=data.commandRoutes[i]; next[data.commandRouteCount]={phrase,url,apiKey,command}; delete[] data.commandRoutes; data.commandRoutes=next; data.commandRouteCount++; return true; }

void ConfigManager::setDefaults(){ clearChats(); clearCommandRoutes(); data.system.deviceName="Emily"; data.system.timezone="Europe/Kyiv"; data.system.ntpServer=NTP_SERVER_1; data.system.botToken=BOT_TOKEN; data.system.hubApiKey=HUB_API_KEY; data.system.startupMessageEnabled=true; data.system.startupMessage="Emily is online 🤖"; data.weather=WeatherConfig(); data.gpio35={false,"",""}; data.gpio39={false,"",""}; }
bool ConfigManager::begin(){ if(!sdCard.isAvailable())return false; setDefaults(); load(); ready=true; return true; }

bool ConfigManager::load(){ if(!SD.exists(CONFIG_FILE))return false; File file=SD.open(CONFIG_FILE,FILE_READ); if(!file)return false; JsonDocument doc; DeserializationError error=deserializeJson(doc,file); file.close(); if(error)return false;
 JsonObject system=doc["system"]; if(system["deviceName"].is<const char*>())data.system.deviceName=system["deviceName"].as<const char*>(); if(system["timezone"].is<const char*>())data.system.timezone=system["timezone"].as<const char*>(); if(system["ntpServer"].is<const char*>())data.system.ntpServer=system["ntpServer"].as<const char*>(); if(system["botToken"].is<const char*>())data.system.botToken=system["botToken"].as<const char*>(); if(system["hubApiKey"].is<const char*>())data.system.hubApiKey=system["hubApiKey"].as<const char*>(); if(!system["startupMessageEnabled"].isNull())data.system.startupMessageEnabled=system["startupMessageEnabled"].as<bool>(); if(system["startupMessage"].is<const char*>())data.system.startupMessage=system["startupMessage"].as<const char*>();
 clearChats(); JsonArray chats=doc["telegram"]["chats"].as<JsonArray>(); for(JsonObject c:chats)addChatInternal(String(c["id"]|""),String(c["name"]|"")); if(!data.chatCount&&strlen(TELEGRAM_CHAT_ID))addChatInternal(TELEGRAM_CHAT_ID,"Default");
 clearCommandRoutes(); JsonArray routes=doc["commands"]["routes"].as<JsonArray>(); for(JsonObject r:routes)addCommandRouteInternal(String(r["phrase"]|""),String(r["url"]|""),String(r["apiKey"]|""),String(r["command"]|""));
 JsonObject g35=doc["gpio35"]; if(!g35["enabled"].isNull())data.gpio35.enabled=g35["enabled"].as<bool>(); if(g35["highMessage"].is<const char*>())data.gpio35.highMessage=g35["highMessage"].as<const char*>(); if(g35["lowMessage"].is<const char*>())data.gpio35.lowMessage=g35["lowMessage"].as<const char*>(); JsonObject g39=doc["gpio39"]; if(!g39["enabled"].isNull())data.gpio39.enabled=g39["enabled"].as<bool>(); if(g39["highMessage"].is<const char*>())data.gpio39.highMessage=g39["highMessage"].as<const char*>(); if(g39["lowMessage"].is<const char*>())data.gpio39.lowMessage=g39["lowMessage"].as<const char*>();
 if(!data.system.deviceName.length())data.system.deviceName="Emily"; if(!data.system.timezone.length())data.system.timezone="Europe/Kyiv"; if(!data.system.ntpServer.length())data.system.ntpServer=NTP_SERVER_1; return true; }

bool ConfigManager::save(){ if(!sdCard.isAvailable())return false; JsonDocument doc; JsonObject s=doc["system"].to<JsonObject>(); s["deviceName"]=data.system.deviceName;s["timezone"]=data.system.timezone;s["ntpServer"]=data.system.ntpServer;s["botToken"]=data.system.botToken;s["hubApiKey"]=data.system.hubApiKey;s["startupMessageEnabled"]=data.system.startupMessageEnabled;s["startupMessage"]=data.system.startupMessage;
 JsonArray chats=doc["telegram"]["chats"].to<JsonArray>();for(size_t i=0;i<data.chatCount;i++){JsonObject c=chats.add<JsonObject>();c["id"]=data.chats[i].id;c["name"]=data.chats[i].name;}
 JsonArray routes=doc["commands"]["routes"].to<JsonArray>();for(size_t i=0;i<data.commandRouteCount;i++){JsonObject r=routes.add<JsonObject>();r["phrase"]=data.commandRoutes[i].phrase;r["url"]=data.commandRoutes[i].url;r["apiKey"]=data.commandRoutes[i].apiKey;r["command"]=data.commandRoutes[i].command;}
 JsonObject g35=doc["gpio35"].to<JsonObject>();g35["enabled"]=data.gpio35.enabled;g35["highMessage"]=data.gpio35.highMessage;g35["lowMessage"]=data.gpio35.lowMessage;JsonObject g39=doc["gpio39"].to<JsonObject>();g39["enabled"]=data.gpio39.enabled;g39["highMessage"]=data.gpio39.highMessage;g39["lowMessage"]=data.gpio39.lowMessage;
 const char* tmp="/data/config.tmp";if(SD.exists(tmp))SD.remove(tmp);File file=SD.open(tmp,FILE_WRITE);if(!file)return false;size_t written=serializeJsonPretty(doc,file);file.flush();file.close();if(!written){SD.remove(tmp);return false;}if(SD.exists(CONFIG_FILE)&&!SD.remove(CONFIG_FILE))return false;return SD.rename(tmp,CONFIG_FILE); }

String ConfigManager::getDeviceName()const{return data.system.deviceName;} String ConfigManager::getTimezone()const{return data.system.timezone;} String ConfigManager::getNtpServer()const{return data.system.ntpServer;} String ConfigManager::getBotToken()const{return data.system.botToken;} String ConfigManager::getHubApiKey()const{return data.system.hubApiKey;} bool ConfigManager::isStartupMessageEnabled()const{return data.system.startupMessageEnabled;} String ConfigManager::getStartupMessage()const{return data.system.startupMessage;}
void ConfigManager::setDeviceName(const String&v){data.system.deviceName=v;}void ConfigManager::setTimezone(const String&v){data.system.timezone=v;}void ConfigManager::setNtpServer(const String&v){data.system.ntpServer=v;}void ConfigManager::setBotToken(const String&v){data.system.botToken=v;}void ConfigManager::setHubApiKey(const String&v){data.system.hubApiKey=v;}void ConfigManager::setStartupMessageEnabled(bool v){data.system.startupMessageEnabled=v;}void ConfigManager::setStartupMessage(const String&v){data.system.startupMessage=v;}
size_t ConfigManager::getChatCount()const{return data.chatCount;}TelegramChatConfig ConfigManager::getChat(size_t i)const{return i<data.chatCount?data.chats[i]:TelegramChatConfig();}String ConfigManager::getChatName(const String&id)const{for(size_t i=0;i<data.chatCount;i++)if(data.chats[i].id==id)return data.chats[i].name;return id;}bool ConfigManager::hasChat(const String&id)const{for(size_t i=0;i<data.chatCount;i++)if(data.chats[i].id==id)return true;return false;}bool ConfigManager::addChat(const String&id,const String&name){return !hasChat(id)&&addChatInternal(id,name);}bool ConfigManager::updateChat(size_t i,const String&id,const String&name){if(i>=data.chatCount||!id.length())return false;for(size_t j=0;j<data.chatCount;j++)if(j!=i&&data.chats[j].id==id)return false;data.chats[i]={id,name.length()?name:id};return true;}bool ConfigManager::deleteChat(size_t i){if(i>=data.chatCount)return false;for(size_t j=i+1;j<data.chatCount;j++)data.chats[j-1]=data.chats[j];data.chatCount--;if(!data.chatCount){delete[] data.chats;data.chats=nullptr;return true;}auto* next=new TelegramChatConfig[data.chatCount];if(!next)return false;for(size_t j=0;j<data.chatCount;j++)next[j]=data.chats[j];delete[] data.chats;data.chats=next;return true;}
size_t ConfigManager::getCommandRouteCount()const{return data.commandRouteCount;}CommandRouteConfig ConfigManager::getCommandRoute(size_t i)const{return i<data.commandRouteCount?data.commandRoutes[i]:CommandRouteConfig();}bool ConfigManager::addCommandRoute(const String&p,const String&u,const String&k,const String&c){return addCommandRouteInternal(p,u,k,c);}bool ConfigManager::updateCommandRoute(size_t i,const String&p,const String&u,const String&k,const String&c){if(i>=data.commandRouteCount||!p.length()||!u.length()||!c.length())return false;data.commandRoutes[i]={p,u,k,c};return true;}bool ConfigManager::deleteCommandRoute(size_t i){if(i>=data.commandRouteCount)return false;for(size_t j=i+1;j<data.commandRouteCount;j++)data.commandRoutes[j-1]=data.commandRoutes[j];data.commandRouteCount--;if(!data.commandRouteCount){delete[] data.commandRoutes;data.commandRoutes=nullptr;return true;}auto* next=new CommandRouteConfig[data.commandRouteCount];if(!next)return false;for(size_t j=0;j<data.commandRouteCount;j++)next[j]=data.commandRoutes[j];delete[] data.commandRoutes;data.commandRoutes=next;return true;}

bool ConfigManager::isWeatherEnabled()const{return false;}String ConfigManager::getWeatherApiKey()const{return "";}String ConfigManager::getWeatherCity()const{return "";}uint8_t ConfigManager::getWeatherHour()const{return 0;}uint8_t ConfigManager::getWeatherMinute()const{return 0;}void ConfigManager::setWeatherEnabled(bool){}void ConfigManager::setWeatherApiKey(const String&){}void ConfigManager::setWeatherCity(const String&){}void ConfigManager::setWeatherTime(uint8_t,uint8_t){}
bool ConfigManager::isGpio35Enabled()const{return data.gpio35.enabled;}String ConfigManager::getGpio35HighMessage()const{return data.gpio35.highMessage;}String ConfigManager::getGpio35LowMessage()const{return data.gpio35.lowMessage;}void ConfigManager::setGpio35Enabled(bool v){data.gpio35.enabled=v;}void ConfigManager::setGpio35HighMessage(const String&v){data.gpio35.highMessage=v;}void ConfigManager::setGpio35LowMessage(const String&v){data.gpio35.lowMessage=v;}bool ConfigManager::isGpio39Enabled()const{return data.gpio39.enabled;}String ConfigManager::getGpio39HighMessage()const{return data.gpio39.highMessage;}String ConfigManager::getGpio39LowMessage()const{return data.gpio39.lowMessage;}void ConfigManager::setGpio39Enabled(bool v){data.gpio39.enabled=v;}void ConfigManager::setGpio39HighMessage(const String&v){data.gpio39.highMessage=v;}void ConfigManager::setGpio39LowMessage(const String&v){data.gpio39.lowMessage=v;}
