#pragma once

#define PROJECT_NAME "Emily"
#define DEVICE_NAME "Emily"

#define ETH_PHY_ADDR 1
#define ETH_PHY_POWER 16
#define ETH_PHY_MDC 23
#define ETH_PHY_MDIO 18
#define ETH_PHY_TYPE ETH_PHY_LAN8720
#define ETH_CLK_MODE ETH_CLOCK_GPIO0_IN

#define BOT_TOKEN "8206398846:AAEfAIcjoywOUI56qQjKpX5kUIQYLM0uchs"
#define ADMIN_CHAT_ID "1351588344"
#define TELEGRAM_CHAT_ID "1351588344"
#define TELEGRAM_CHECK_INTERVAL 1000

#define LED_TX_PIN 4
#define LED_RX_PIN 5
#define LED_ACTIVITY_DURATION 150UL

#define GMT_OFFSET_SEC 7200
#define DAYLIGHT_OFFSET_SEC 3600
#define NTP_SERVER_1 "pool.ntp.org"
#define NTP_SERVER_2 "time.nist.gov"

#define STATISTICS_UPDATE_INTERVAL 1000
#define STATISTICS_SAVE_INTERVAL 900000UL

#define HUB_API_KEY "emily-secret-key"
