#include "WebServerManager.h"
#include <ETH.h>
#include "../core/ConfigManager.h"
#include "../services/ReminderManager.h"
#include "TelegramManager.h"

WebServerManager webServerManager;

static bool readReminder(WebServer& s, Reminder& r, bool edit){String msg=s.arg("message"),chat=s.arg("chatId"),type=s.arg("type"),tm=s.arg("time");msg.trim();chat.trim();if(!msg.length()||!config.hasChat(chat)||tm.length()!=5)return false;r.message=msg;r.chatId=chat;r.silent=s.hasArg("silent");r.enabled=edit?s.hasArg("enabled"):true;r.hour=tm.substring(0,2).toInt();r.minute=tm.substring(3,5).toInt();if(r.hour<0||r.hour>23||r.minute<0||r.minute>59)return false;if(type=="daily")r.type=ReminderType::DAILY;else if(type=="weekly")r.type=ReminderType::WEEKLY;else if(type=="monthly")r.type=ReminderType::MONTHLY;else if(type=="yearly")r.type=ReminderType::YEARLY;else r.type=ReminderType::ONCE;if(r.type==ReminderType::ONCE){String d=s.arg("onceDate");if(d.length()!=10)return false;r.year=d.substring(0,4).toInt();r.month=d.substring(5,7).toInt();r.day=d.substring(8,10).toInt();return r.year>=2000&&r.month>=1&&r.month<=12&&r.day>=1&&r.day<=31;}if(r.type==ReminderType::WEEKLY){r.weekday=s.arg("weekday").toInt();return r.weekday>=0&&r.weekday<=6;}if(r.type==ReminderType::MONTHLY){r.day=s.arg("monthlyDay").toInt();return r.day>=1&&r.day<=31;}if(r.type==ReminderType::YEARLY){r.day=s.arg("yearlyDay").toInt();r.month=s.arg("yearlyMonth").toInt();return r.day>=1&&r.day<=31&&r.month>=1&&r.month<=12;}return true;}

void WebServerManager::begin(){
    server.on("/",HTTP_GET,[this](){server.sendHeader("Location","/sd/");server.send(303);});
    server.on("/settings",HTTP_GET,[this](){server.sendHeader("Location","/sd/settings.html");server.send(303);});
    server.on("/reminders",HTTP_GET,[this](){server.sendHeader("Location","/sd/reminders.html");server.send(303);});
    server.on("/api/secrets",HTTP_GET,[this](){String j="{\"botToken\":\""+config.getBotToken()+"\",\"hubApiKey\":\""+config.getHubApiKey()+"\"}";server.send(200,"application/json; charset=utf-8",j);});
    server.on("/settings/save",HTTP_POST,[this](){handleSaveSettings();});server.on("/settings/chat/add",HTTP_POST,[this](){handleAddChat();});server.on("/settings/chat/edit",HTTP_POST,[this](){handleUpdateChat();});server.on("/settings/chat/delete",HTTP_POST,[this](){handleDeleteChat();});
    server.on("/reminders/add",HTTP_POST,[this](){handleAddReminder();});server.on("/reminders/edit",HTTP_POST,[this](){handleUpdateReminder();});server.on("/reminders/clone",HTTP_POST,[this](){handleCloneReminder();});server.on("/reminders/delete",HTTP_POST,[this](){handleDeleteReminder();});server.on("/reminders/toggle",HTTP_POST,[this](){handleToggleReminder();});server.on("/api/telegram/send",HTTP_POST,[this](){handleHubTelegramSend();});server.onNotFound([this](){handleNotFound();});server.begin();Serial.printf("[WEB] Started: http://%s\n",ETH.localIP().toString().c_str());}
void WebServerManager::update(){server.handleClient();}
void WebServerManager::handleSaveSettings(){String oldToken=config.getBotToken();config.setDeviceName(server.arg("deviceName"));config.setTimezone(server.arg("timezone"));config.setNtpServer(server.arg("ntpServer"));config.setBotToken(server.arg("botToken"));config.setHubApiKey(server.arg("hubApiKey"));config.setStartupMessageEnabled(server.hasArg("startupMessageEnabled"));config.setStartupMessage(server.arg("startupMessage"));config.setGpio35Enabled(server.hasArg("gpio35Enabled"));config.setGpio35HighMessage(server.arg("gpio35HighMessage"));config.setGpio35LowMessage(server.arg("gpio35LowMessage"));config.setGpio39Enabled(server.hasArg("gpio39Enabled"));config.setGpio39HighMessage(server.arg("gpio39HighMessage"));config.setGpio39LowMessage(server.arg("gpio39LowMessage"));if(!config.save()){server.send(500,"text/plain","Save failed");return;}String newToken=config.getBotToken();newToken.trim();if(newToken!=oldToken){if(!telegram.reloadToken()){server.send(400,"text/plain","Saved, but Telegram token is empty");return;}}server.send(200,"text/plain","OK");}
void WebServerManager::handleAddChat(){String id=server.arg("id"),name=server.arg("name");id.trim();name.trim();if(!id.length()||!name.length()||!config.addChat(id,name)||!config.save()){server.send(400,"text/plain","Failed to add chat");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleUpdateChat(){size_t i=(size_t)server.arg("index").toInt();String id=server.arg("id"),name=server.arg("name");id.trim();name.trim();if(!id.length()||!name.length()||i>=config.getChatCount()||!config.updateChat(i,id,name)||!config.save()){server.send(400,"text/plain","Failed to update chat");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleDeleteChat(){size_t i=(size_t)server.arg("index").toInt();if(i>=config.getChatCount()||!config.deleteChat(i)||!config.save()){server.send(400,"text/plain","Failed to delete chat");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleAddReminder(){Reminder r;if(!readReminder(server,r,false)){server.send(400,"text/plain","Invalid reminder");return;}if(!reminderManager.addReminder(r)){server.send(500,"text/plain","Failed to add reminder");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleUpdateReminder(){uint32_t id=(uint32_t)server.arg("id").toInt();Reminder r;if(!id||!reminderManager.getReminderById(id,r)||!readReminder(server,r,true)){server.send(400,"text/plain","Invalid reminder");return;}if(!reminderManager.updateReminder(r)){server.send(500,"text/plain","Failed to update reminder");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleCloneReminder(){uint32_t id=(uint32_t)server.arg("id").toInt();Reminder r;if(!id||!reminderManager.getReminderById(id,r)){server.send(404,"text/plain","Reminder not found");return;}r.id=0;r.lastTriggered=0;r.nextTrigger=0;if(!reminderManager.addReminder(r)){server.send(500,"text/plain","Failed to clone reminder");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleDeleteReminder(){uint32_t id=(uint32_t)server.arg("id").toInt();if(!id||!reminderManager.deleteReminder(id)){server.send(404,"text/plain","Reminder not found");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleToggleReminder(){uint32_t id=(uint32_t)server.arg("id").toInt();bool enabled=server.arg("enabled")=="1"||server.arg("enabled")=="true";if(!id||!reminderManager.setEnabled(id,enabled)){server.send(400,"text/plain","Failed to update reminder");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleHubTelegramSend(){String apiKey=server.arg("apiKey"),chatId=server.arg("chatId"),text=server.arg("text");bool silent=server.arg("silent")=="1"||server.arg("silent")=="true";if(apiKey!=config.getHubApiKey()){server.send(403,"text/plain","Invalid API key");return;}if(!config.hasChat(chatId)){server.send(400,"text/plain","Unknown chat");return;}if(!text.length()||!telegram.sendMessage(chatId,text,silent)){server.send(500,"text/plain","Telegram send failed");return;}server.send(200,"text/plain","OK");}
void WebServerManager::handleNotFound(){server.send(404,"text/plain; charset=utf-8","404 - Not found");}
