#include "WebServerManager.h"
#include <ETH.h>
#include <SD.h>
#include "../core/ConfigManager.h"
#include "../core/Statistics.h"
#include "../storage/SDCardManager.h"
#include "../services/ReminderManager.h"
#include "../services/TimeManager.h"
#include "TelegramManager.h"

WebServerManager webServerManager;

static String esc(String s){s.replace("&","&amp;");s.replace("<","&lt;");s.replace(">","&gt;");s.replace("\"","&quot;");s.replace("'","&#39;");return s;}

void WebServerManager::begin(){
 server.on("/",HTTP_GET,[this](){handleRoot();});
 server.on("/settings",HTTP_GET,[this](){handleSettings();});
 server.on("/settings/save",HTTP_POST,[this](){handleSaveSettings();});
 server.on("/settings/chat/add",HTTP_POST,[this](){handleAddChat();});
 server.on("/settings/chat/delete",HTTP_POST,[this](){handleDeleteChat();});
 server.on("/reminders",HTTP_GET,[this](){handleReminders();});
 server.on("/reminders/add",HTTP_POST,[this](){handleAddReminder();});
 server.on("/reminders/delete",HTTP_POST,[this](){handleDeleteReminder();});
 server.on("/reminders/toggle",HTTP_POST,[this](){handleToggleReminder();});
 server.on("/api/telegram/send",HTTP_POST,[this](){handleHubTelegramSend();});
 server.onNotFound([this](){handleNotFound();});server.begin();
 Serial.printf("[WEB] Started: http://%s\n",ETH.localIP().toString().c_str());
}
void WebServerManager::update(){server.handleClient();}

void WebServerManager::handleRoot(){String h=getPageHeader(config.getDeviceName())+getNavigation()+"<h1>"+esc(config.getDeviceName())+"</h1>";
 h+="<div class='card'><h2>Network</h2><p><b>Status:</b> "+String(ETH.linkUp()?"Online":"Offline")+"</p><p><b>IP:</b> "+ETH.localIP().toString()+"</p><p><b>Gateway:</b> "+ETH.gatewayIP().toString()+"</p><p><b>Speed:</b> "+String(ETH.linkSpeed())+" Mbps</p></div>";
 h+="<div class='card'><h2>System</h2><p><b>Time:</b> "+timeManager.getDateTimeString()+"</p><p><b>Total uptime:</b> "+statistics.getTotalUptimeString()+"</p><p><b>Session:</b> "+statistics.getCurrentUptimeString()+"</p><p><b>Boots:</b> "+String(statistics.getBootCount())+"</p></div>";
 h+="<div class='card'><h2>Telegram</h2><p><b>Chats:</b> "+String(config.getChatCount())+"</p><p><b>Sent:</b> "+String(statistics.getMessagesSent())+"</p><p><b>Received:</b> "+String(statistics.getMessagesReceived())+"</p></div>";
 server.send(200,"text/html; charset=utf-8",h+getPageFooter());}

void WebServerManager::handleSettings(){String h=getPageHeader("Settings")+getNavigation()+"<h1>Settings</h1><form method='POST' action='/settings/save'>";
 h+="<div class='card'><h2>System</h2><label>Device name</label><input name='deviceName' value='"+esc(config.getDeviceName())+"'><label>Timezone</label><input name='timezone' value='"+esc(config.getTimezone())+"'><label>NTP server</label><input name='ntpServer' value='"+esc(config.getNtpServer())+"'></div>";
 h+="<div class='card'><h2>API and tokens</h2><label>Telegram bot token</label><input type='password' name='botToken' value='"+esc(config.getBotToken())+"'><label>Hub API key</label><input type='password' name='hubApiKey' value='"+esc(config.getHubApiKey())+"'></div>";
 h+="<div class='card'><h2>Startup message</h2><label class='checkbox'><input type='checkbox' name='startupMessageEnabled' "+String(config.isStartupMessageEnabled()?"checked":"")+"> Send after startup</label><label>Message</label><textarea name='startupMessage' rows='4'>"+esc(config.getStartupMessage())+"</textarea></div>";
 h+="<div class='card'><h2>GPIO Monitor</h2><h3>GPIO 35</h3><label class='checkbox'><input type='checkbox' name='gpio35Enabled' "+String(config.isGpio35Enabled()?"checked":"")+"> Enable</label><label>Message HIGH</label><input name='gpio35HighMessage' value='"+esc(config.getGpio35HighMessage())+"'><label>Message LOW</label><input name='gpio35LowMessage' value='"+esc(config.getGpio35LowMessage())+"'><h3>GPIO 39</h3><label class='checkbox'><input type='checkbox' name='gpio39Enabled' "+String(config.isGpio39Enabled()?"checked":"")+"> Enable</label><label>Message HIGH</label><input name='gpio39HighMessage' value='"+esc(config.getGpio39HighMessage())+"'><label>Message LOW</label><input name='gpio39LowMessage' value='"+esc(config.getGpio39LowMessage())+"'></div><button type='submit'>Save settings</button></form>";
 h+="<div class='card'><h2>Telegram chats</h2>";
 for(size_t i=0;i<config.getChatCount();i++){auto c=config.getChat(i);h+="<div class='chat'><b>"+esc(c.name)+"</b><br><code>"+esc(c.id)+"</code><form method='POST' action='/settings/chat/delete'><input type='hidden' name='index' value='"+String(i)+"'><button class='danger'>Delete</button></form></div>";}
 h+="<h3>Add chat</h3><form method='POST' action='/settings/chat/add'><label>Chat name</label><input name='name' required><label>Chat ID</label><input name='id' required><button>Add chat</button></form></div>";
 server.send(200,"text/html; charset=utf-8",h+getPageFooter());}

void WebServerManager::handleSaveSettings(){config.setDeviceName(server.arg("deviceName"));config.setTimezone(server.arg("timezone"));config.setNtpServer(server.arg("ntpServer"));config.setBotToken(server.arg("botToken"));config.setHubApiKey(server.arg("hubApiKey"));config.setStartupMessageEnabled(server.hasArg("startupMessageEnabled"));config.setStartupMessage(server.arg("startupMessage"));config.setGpio35Enabled(server.hasArg("gpio35Enabled"));config.setGpio35HighMessage(server.arg("gpio35HighMessage"));config.setGpio35LowMessage(server.arg("gpio35LowMessage"));config.setGpio39Enabled(server.hasArg("gpio39Enabled"));config.setGpio39HighMessage(server.arg("gpio39HighMessage"));config.setGpio39LowMessage(server.arg("gpio39LowMessage"));if(!config.save()){server.send(500,"text/plain","Save failed");return;}server.sendHeader("Location","/settings");server.send(303);}
void WebServerManager::handleAddChat(){String id=server.arg("id"),name=server.arg("name");id.trim();name.trim();if(!id.length()||!config.addChat(id,name)||!config.save()){server.send(400,"text/plain","Failed to add chat");return;}server.sendHeader("Location","/settings");server.send(303);}
void WebServerManager::handleDeleteChat(){size_t i=(size_t)server.arg("index").toInt();if(!config.deleteChat(i)||!config.save()){server.send(400,"text/plain","Failed to delete chat");return;}server.sendHeader("Location","/settings");server.send(303);}

void WebServerManager::handleReminders(){const size_t pp=20,total=reminderManager.getCount();size_t pages=(total+pp-1)/pp;if(!pages)pages=1;size_t page=server.hasArg("page")?(size_t)server.arg("page").toInt():1;if(page<1)page=1;if(page>pages)page=pages;size_t first=(page-1)*pp,last=first+pp;if(last>total)last=total;String h=getPageHeader("Reminders")+getNavigation()+"<h1>Reminders</h1><div class='card'><h2>My reminders ("+String(total)+")</h2>";
 for(size_t i=first;i<last;i++){Reminder r=reminderManager.getReminder(i);h+="<div class='card reminder "+String(r.enabled?"":"disabled")+"'><h3>"+esc(r.message)+"</h3><p><b>Chat:</b> "+esc(config.getChatName(r.chatId))+"</p><p><b>Time:</b> "+String(r.hour<10?"0":"")+String(r.hour)+":"+String(r.minute<10?"0":"")+String(r.minute)+"</p><p><b>Notification:</b> "+String(r.silent?"Silent":"With sound")+"</p><form method='POST' action='/reminders/toggle'><input type='hidden' name='id' value='"+String(r.id)+"'><input type='hidden' name='enabled' value='"+String(r.enabled?0:1)+"'><button>"+String(r.enabled?"Disable":"Enable")+"</button></form><form method='POST' action='/reminders/delete'><input type='hidden' name='id' value='"+String(r.id)+"'><button class='danger'>Delete</button></form></div>";}
 h+="<div class='pagination'>";if(page>1)h+="<a href='/reminders?page="+String(page-1)+"'>← Previous</a>";h+=" Page "+String(page)+" / "+String(pages)+" ";if(page<pages)h+="<a href='/reminders?page="+String(page+1)+"'>Next →</a>";h+="</div></div>";
 h+="<div class='card'><h2>Add reminder</h2><form method='POST' action='/reminders/add'><label>Message</label><textarea name='message' required></textarea><label>Chat</label><select name='chatId'>";for(size_t i=0;i<config.getChatCount();i++){auto c=config.getChat(i);h+="<option value='"+esc(c.id)+"'>"+esc(c.name)+"</option>";}h+="</select><label>Repeat</label><select name='type' id='type' onchange='f()'><option value='once'>Once</option><option value='daily'>Every day</option><option value='weekly'>Every week</option><option value='monthly'>Every month</option><option value='yearly'>Every year</option></select><div id='once'><label>Date</label><input type='date' name='onceDate'></div><div id='weekly'><label>Weekday</label><select name='weekday'><option value='0'>Sunday</option><option value='1'>Monday</option><option value='2'>Tuesday</option><option value='3'>Wednesday</option><option value='4'>Thursday</option><option value='5'>Friday</option><option value='6'>Saturday</option></select></div><div id='monthly'><label>Day</label><input type='number' name='monthlyDay' min='1' max='31' value='1'></div><div id='yearly'><label>Day</label><input type='number' name='yearlyDay' min='1' max='31' value='1'><label>Month</label><input type='number' name='yearlyMonth' min='1' max='12' value='1'></div><label>Time</label><input type='time' name='time' value='09:00' required><label class='checkbox'><input type='checkbox' name='silent'> Send without sound</label><button>Add reminder</button></form><script>function f(){let t=document.getElementById('type').value;for(let x of ['once','weekly','monthly','yearly'])document.getElementById(x).style.display=t===x?'block':'none'}f()</script></div>";
 server.send(200,"text/html; charset=utf-8",h+getPageFooter());}

void WebServerManager::handleAddReminder(){Reminder r;r.message=server.arg("message");r.message.trim();r.chatId=server.arg("chatId");if(!r.message.length()||!config.hasChat(r.chatId)){server.send(400,"text/plain","Invalid reminder");return;}String ty=server.arg("type"),t=server.arg("time");if(ty=="daily")r.type=ReminderType::DAILY;else if(ty=="weekly")r.type=ReminderType::WEEKLY;else if(ty=="monthly")r.type=ReminderType::MONTHLY;else if(ty=="yearly")r.type=ReminderType::YEARLY;else r.type=ReminderType::ONCE;if(t.length()!=5){server.send(400,"text/plain","Invalid time");return;}r.hour=t.substring(0,2).toInt();r.minute=t.substring(3,5).toInt();r.silent=server.hasArg("silent");if(r.type==ReminderType::ONCE){String d=server.arg("onceDate");if(d.length()!=10){server.send(400,"text/plain","Date required");return;}r.year=d.substring(0,4).toInt();r.month=d.substring(5,7).toInt();r.day=d.substring(8,10).toInt();}else if(r.type==ReminderType::WEEKLY)r.weekday=server.arg("weekday").toInt();else if(r.type==ReminderType::MONTHLY)r.day=server.arg("monthlyDay").toInt();else if(r.type==ReminderType::YEARLY){r.day=server.arg("yearlyDay").toInt();r.month=server.arg("yearlyMonth").toInt();}if(!reminderManager.addReminder(r)){server.send(500,"text/plain","Failed to create reminder");return;}server.sendHeader("Location","/reminders");server.send(303);}
void WebServerManager::handleToggleReminder(){uint32_t id=server.arg("id").toInt();if(!reminderManager.setEnabled(id,server.arg("enabled").toInt()==1)){server.send(404,"text/plain","Not found");return;}server.sendHeader("Location","/reminders");server.send(303);}
void WebServerManager::handleDeleteReminder(){uint32_t id=server.arg("id").toInt();if(!id||!reminderManager.deleteReminder(id)){server.send(404,"text/plain","Not found");return;}server.sendHeader("Location","/reminders");server.send(303);}

void WebServerManager::handleHubTelegramSend(){String key=server.header("X-API-Key");if(!key.length())key=server.arg("apiKey");if(key!=config.getHubApiKey()){server.send(401,"application/json","{\"ok\":false,\"error\":\"Unauthorized\"}");return;}String chatId=server.arg("chatId"),message=server.arg("message");if(!chatId.length()&&config.getChatCount())chatId=config.getChat(0).id;if(!message.length()){server.send(400,"application/json","{\"ok\":false,\"error\":\"Message required\"}");return;}bool silent=server.arg("silent")=="1"||server.arg("silent")=="true";bool ok=telegram.sendMessage(chatId,message,silent);server.send(ok?200:502,"application/json",ok?"{\"ok\":true}":"{\"ok\":false}");}
void WebServerManager::handleNotFound(){server.send(404,"text/plain","404 - Not found");}
String WebServerManager::getPageHeader(const String& t){return "<!DOCTYPE html><html><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>"+esc(t)+"</title><style>*{box-sizing:border-box}body{margin:0;font-family:Arial;background:#f4f6f8;color:#222}.container{max-width:900px;margin:auto;padding:20px}nav{background:#222;padding:12px;border-radius:8px}nav a{color:#fff;text-decoration:none;margin-right:20px}.card{background:#fff;padding:20px;margin:20px 0;border-radius:8px;box-shadow:0 2px 5px #0002}label{display:block;margin-top:14px;font-weight:bold}input,textarea,select{width:100%;padding:10px;margin-top:5px;border:1px solid #ccc;border-radius:5px;font-size:16px}.checkbox{display:flex;align-items:center;gap:8px}.checkbox input{width:auto;margin:0}button{padding:10px 16px;margin-top:12px;border:0;border-radius:5px;background:#333;color:#fff}.danger{background:#b42318}.chat{padding:12px;border-bottom:1px solid #ddd}.chat form,.reminder form{display:inline-block;margin-right:8px}.disabled{opacity:.55}.pagination{text-align:center;margin:15px}footer{text-align:center;color:#777;padding:20px}</style></head><body><div class='container'>";}
String WebServerManager::getNavigation(){return "<nav><a href='/'>Home</a><a href='/settings'>Settings</a><a href='/reminders'>Reminders</a></nav>";}
String WebServerManager::getPageFooter(){return "<footer>"+esc(config.getDeviceName())+" Assistant</footer></div></body></html>";}
